name: Build Game

on:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v1

    - name: Configure
      run: |
        mkdir build && cd build
        cmake -G Xcode ..

    - name: Build
      run: |
        xcodebuild -scheme BadPiggies -configuration Release -destination platform=iOS -archivePath ./BadPiggies.xcarchive CODE_SIGNING_ALLOWED=NO
        xcodebuild -exportArchive -exportFormat ipa -archivePath ./BadPiggies.xcarchive -exportPath ./output/BadPiggies.ipa

    - uses: actions/upload-artifact@v4
      with:
        name: BadPiggies-iOS
        path: ./output/BadPiggies.ipa
